apiVersion: v1
kind: Pod
metadata:
  name: awscli-noirsa
  namespace: irsa-lab
  labels:
    app: awscli-test
    mode: noirsa
spec:
  serviceAccountName: default
  containers:
  - name: awscli
    image: public.ecr.aws/aws-cli/aws-cli:latest
    command: ["sh","-c","sleep 3600"]
    env:
    - name: AWS_REGION
      value: "us-west-2"
