apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: energy-dev
  labels:
    app: php-apache
    kube-green.dev/include: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
        kube-green.dev/include: "true"
    spec:
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  namespace: energy-dev
  labels:
    app: php-apache
spec:
  selector:
    app: php-apache
  ports:
  - name: http
    port: 80
    targetPort: 80
