apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-burn
  namespace: energy-demo
  labels:
    app: cpu-burn
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cpu-burn
  template:
    metadata:
      labels:
        app: cpu-burn
    spec:
      containers:
      - name: burner
        image: busybox:1.36
        command: ["sh","-c"]
        args:
          - >
            echo "Burning CPU..." ;
            while true; do
              dd if=/dev/zero of=/dev/null bs=1M count=1024 2>/dev/null;
            done
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
