apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-deployer
  namespace: rbac-dev
rules:
# Deployments/ReplicaSets: CI puede crear/actualizar/eliminar workloads
- apiGroups: ["apps"]
  resources: ["deployments","replicasets"]
  verbs: ["get","list","watch","create","update","patch","delete"]
# Services/ConfigMaps: CI puede gestionar config no sensible
- apiGroups: [""]
  resources: ["services","configmaps"]
  verbs: ["get","list","watch","create","update","patch","delete"]
# Pods/Events: solo lectura (para troubleshooting)
- apiGroups: [""]
  resources: ["pods","events"]
  verbs: ["get","list","watch"]
# Least privilege: NO secrets, NO RBAC objects, NO exec
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-logs
  namespace: rbac-dev
rules:
- apiGroups: [""]
  resources: ["pods","pods/log","events"]
  verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-exec
  namespace: rbac-dev
rules:
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
