apiVersion: v1
kind: LimitRange
metadata:
  name: energy-defaults
  namespace: energy-dev
spec:
  limits:
  - type: Container
    max:
      cpu: "600m"
      memory: "512Mi"
    min:
      cpu: "50m"
      memory: "64Mi"
    default:
      cpu: "300m"
      memory: "256Mi"
    defaultRequest:
      cpu: "150m"
      memory: "128Mi"
