apiVersion: v1
kind: ResourceQuota
metadata:
  name: energy-quota
  namespace: energy-dev
spec:
  hard:
    requests.cpu: "1"
    limits.cpu: "2"
    requests.memory: "1Gi"
    limits.memory: "2Gi"
    pods: "10"
