apiVersion: v1
kind: Pod
metadata:
  name: bad-pod
  namespace: energy-dev
spec:
  containers:
  - name: c
    image: busybox:1.36
    command: ["sh","-c","sleep 3600"]
    resources:
      requests:
        cpu: "800m"
        memory: "700Mi"
