apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sqs-worker-scaledobject
  namespace: keda-demo
spec:
  scaleTargetRef:
    name: sqs-worker
  pollingInterval: 10
  cooldownPeriod: 30
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: aws-pod-identity
    metadata:
      queueURL: "https://sqs.us-west-2.amazonaws.com/521544910957/keda-lab-queue-20260219110120"
      awsRegion: "us-west-2"
      queueLength: "5"
      identityOwner: operator
      activationQueueLength: "1"
